// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type RavelHash struct {
	ID        int32
	ImagePath string
	RavelPost string
	FullHash  int64
	HashPart1 int16
	HashPart2 int16
	HashPart3 int16
	HashPart4 int16
	RavelID   int32
	Permalink string
	PostName  string
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedPassword string
}

type VerifyToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
	ExpiresAt time.Time
	Used      sql.NullBool
}
