// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ravel_hashes.sql

package database

import (
	"context"
)

const createRavelHash = `-- name: CreateRavelHash :one
INSERT INTO ravel_hashes(image_path, ravel_post, full_hash,hash_part_1,hash_part_2, hash_part_3,hash_part_4, ravel_id, permalink, post_name)
values(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10)
RETURNING id, image_path, ravel_post, full_hash, hash_part_1, hash_part_2, hash_part_3, hash_part_4, ravel_id, permalink, post_name
`

type CreateRavelHashParams struct {
	ImagePath string
	RavelPost string
	FullHash  int64
	HashPart1 int16
	HashPart2 int16
	HashPart3 int16
	HashPart4 int16
	RavelID   int32
	Permalink string
	PostName  string
}

func (q *Queries) CreateRavelHash(ctx context.Context, arg CreateRavelHashParams) (RavelHash, error) {
	row := q.db.QueryRowContext(ctx, createRavelHash,
		arg.ImagePath,
		arg.RavelPost,
		arg.FullHash,
		arg.HashPart1,
		arg.HashPart2,
		arg.HashPart3,
		arg.HashPart4,
		arg.RavelID,
		arg.Permalink,
		arg.PostName,
	)
	var i RavelHash
	err := row.Scan(
		&i.ID,
		&i.ImagePath,
		&i.RavelPost,
		&i.FullHash,
		&i.HashPart1,
		&i.HashPart2,
		&i.HashPart3,
		&i.HashPart4,
		&i.RavelID,
		&i.Permalink,
		&i.PostName,
	)
	return i, err
}

const getRavelHashes = `-- name: GetRavelHashes :many
SELECT image_path, ravel_post, full_hash, ravel_id, permalink, post_name
FROM ravel_hashes
WHERE hash_part_1 = $1 
   OR hash_part_2 = $2 
   OR hash_part_3 = $3 
   OR hash_part_4 = $4
`

type GetRavelHashesParams struct {
	HashPart1 int16
	HashPart2 int16
	HashPart3 int16
	HashPart4 int16
}

type GetRavelHashesRow struct {
	ImagePath string
	RavelPost string
	FullHash  int64
	RavelID   int32
	Permalink string
	PostName  string
}

func (q *Queries) GetRavelHashes(ctx context.Context, arg GetRavelHashesParams) ([]GetRavelHashesRow, error) {
	rows, err := q.db.QueryContext(ctx, getRavelHashes,
		arg.HashPart1,
		arg.HashPart2,
		arg.HashPart3,
		arg.HashPart4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRavelHashesRow
	for rows.Next() {
		var i GetRavelHashesRow
		if err := rows.Scan(
			&i.ImagePath,
			&i.RavelPost,
			&i.FullHash,
			&i.RavelID,
			&i.Permalink,
			&i.PostName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetRavelHashes = `-- name: ResetRavelHashes :exec
DELETE FROM ravel_hashes
`

func (q *Queries) ResetRavelHashes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetRavelHashes)
	return err
}
