// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_searches.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSearchResult = `-- name: CreateSearchResult :one
INSERT INTO search_result(id, name, permalink, image_path, search_id)
values(
$1,
$2,
$3,
$4,
$5)
RETURNING id, name, permalink, image_path, search_id
`

type CreateSearchResultParams struct {
	ID        uuid.UUID
	Name      string
	Permalink string
	ImagePath string
	SearchID  uuid.UUID
}

func (q *Queries) CreateSearchResult(ctx context.Context, arg CreateSearchResultParams) (SearchResult, error) {
	row := q.db.QueryRowContext(ctx, createSearchResult,
		arg.ID,
		arg.Name,
		arg.Permalink,
		arg.ImagePath,
		arg.SearchID,
	)
	var i SearchResult
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Permalink,
		&i.ImagePath,
		&i.SearchID,
	)
	return i, err
}

const createUserSearch = `-- name: CreateUserSearch :one
INSERT INTO user_search(id, created_at, updated_at, user_id, search_img)
values(
$1,
$2,
$3,
$4,
$5)
RETURNING id, created_at, updated_at, search_img, user_id
`

type CreateUserSearchParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	SearchImg string
}

func (q *Queries) CreateUserSearch(ctx context.Context, arg CreateUserSearchParams) (UserSearch, error) {
	row := q.db.QueryRowContext(ctx, createUserSearch,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.SearchImg,
	)
	var i UserSearch
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchImg,
		&i.UserID,
	)
	return i, err
}

const getUserSearchResults = `-- name: GetUserSearchResults :many
SELECT id, name, permalink, image_path, search_id FROM search_result WHERE search_id = $1
`

func (q *Queries) GetUserSearchResults(ctx context.Context, searchID uuid.UUID) ([]SearchResult, error) {
	rows, err := q.db.QueryContext(ctx, getUserSearchResults, searchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchResult
	for rows.Next() {
		var i SearchResult
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Permalink,
			&i.ImagePath,
			&i.SearchID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSearches = `-- name: GetUserSearches :many
SELECT id, created_at, updated_at, search_img, user_id FROM user_search WHERE user_id = $1 ORDER BY created_at ASC
`

func (q *Queries) GetUserSearches(ctx context.Context, userID uuid.UUID) ([]UserSearch, error) {
	rows, err := q.db.QueryContext(ctx, getUserSearches, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserSearch
	for rows.Next() {
		var i UserSearch
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchImg,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetSearchResult = `-- name: ResetSearchResult :exec
DELETE FROM search_result
`

func (q *Queries) ResetSearchResult(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetSearchResult)
	return err
}

const resetUserSearch = `-- name: ResetUserSearch :exec
DELETE FROM user_search
`

func (q *Queries) ResetUserSearch(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetUserSearch)
	return err
}
