// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: verify_tokens.sql

package database

import (
	"context"
	"time"
)

const createVerifyToken = `-- name: CreateVerifyToken :one
INSERT INTO verify_tokens( token, created_at, updated_at, email, expires_at, used)
values(
    $1,
    $2,
    $3,
    $4,
    $5,
    FALSE)
RETURNING token, created_at, updated_at, email, expires_at, used
`

type CreateVerifyTokenParams struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
	ExpiresAt time.Time
}

func (q *Queries) CreateVerifyToken(ctx context.Context, arg CreateVerifyTokenParams) (VerifyToken, error) {
	row := q.db.QueryRowContext(ctx, createVerifyToken,
		arg.Token,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Email,
		arg.ExpiresAt,
	)
	var i VerifyToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.ExpiresAt,
		&i.Used,
	)
	return i, err
}

const deleteVerifyTokenFromEmail = `-- name: DeleteVerifyTokenFromEmail :exec
DELETE FROM verify_tokens WHERE email = $1
`

func (q *Queries) DeleteVerifyTokenFromEmail(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, deleteVerifyTokenFromEmail, email)
	return err
}

const getVerifyToken = `-- name: GetVerifyToken :one
SELECT token, created_at, updated_at, email, expires_at, used FROM verify_tokens WHERE token = $1 LIMIT 1
`

func (q *Queries) GetVerifyToken(ctx context.Context, token string) (VerifyToken, error) {
	row := q.db.QueryRowContext(ctx, getVerifyToken, token)
	var i VerifyToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.ExpiresAt,
		&i.Used,
	)
	return i, err
}

const getVerifyTokenFromId = `-- name: GetVerifyTokenFromId :one
SELECT token, created_at, updated_at, email, expires_at, used FROM verify_tokens WHERE email = $1 LIMIT 1
`

func (q *Queries) GetVerifyTokenFromId(ctx context.Context, email string) (VerifyToken, error) {
	row := q.db.QueryRowContext(ctx, getVerifyTokenFromId, email)
	var i VerifyToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.ExpiresAt,
		&i.Used,
	)
	return i, err
}

const resetVerifyTokens = `-- name: ResetVerifyTokens :exec
DELETE FROM verify_tokens
`

func (q *Queries) ResetVerifyTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetVerifyTokens)
	return err
}

const useVerifyToken = `-- name: UseVerifyToken :exec
UPDATE verify_tokens 
SET used = 1, updated_at = $1 WHERE token = $1
`

func (q *Queries) UseVerifyToken(ctx context.Context, updatedAt time.Time) error {
	_, err := q.db.ExecContext(ctx, useVerifyToken, updatedAt)
	return err
}
